{ ... }: {
  flake.modules.nixos.packages = { pkgs, ... }: {
    environment.systemPackages = with pkgs; [
      adbfs-rootless
      adminneo
      adwaita-icon-theme
      adw-gtk3
      android-tools
      audacity
      bat
      bibata-cursors
      brave
      brightnessctl
      cava
      cliphist
      eza
      fastfetch
      fzf
      git
      gnumake
      imv
      jmtpfs
      jq
      kdePackages.qt6ct
      kitty
      lazygit
      libreoffice-fresh
      localsend
      mariadb
      mycli
      mpv
      mysql-workbench
      netbeans
      nodejs
      obs-studio
      opencode
      playerctl
      ripgrep
      tldr
      trash-cli
      tree-sitter
      unar
      unzip
      aria2
      wget
      xwayland-satellite
      yazi
      zathura
      zoxide
      atuin
      bat-extras.batdiff
      bat-extras.batman
      delta
      dust
      libva-utils
      intel-gpu-tools
      nh
      ouch
      pay-respects
      pavucontrol
      procs
      tokei
      watchexec
      wl-clipboard
      yq
      gh
    ];
  };
}
